### ISSUE TITLE
Error: cannot subset by character when rownames are NULL

### ISSUE THREAD

**Issue by hliu2016** [hbc/bcbioRNASeq#98]
Hi, I am running the functional analysis template. The command `entrez <- rowData(bcb)[all_genes, "entrezID", drop = TRUE]` in the KEGG enrichment analysis throwed this error.

Could you help to work out it?

**Comment by mjsteinbaugh** [comment]
I noticed this too last week and am fixing it on the develop branch. I'm working on pushing this to master this week and will post an update here. 

The draft code is here if you want to try tweaking your template in the meantime:
https://github.com/hbc/bcbioRNASeq/blob/develop/inst/rmarkdown/templates/functional_analysis/skeleton/skeleton.Rmd#kegg-enrichment-analysis

**Comment by mjsteinbaugh** [comment]
Thanks you're right, I just updated that on the develop branch. `org_db` should be defined with:

```r
org_db <- paste("org", params$organism, "eg", "db", sep = ".")
```

This should return a value like `org.Hs.eg.db`

**Comment by hliu2016** [comment]
@mjsteinbaugh，
Thanks for your updation. However, the rmarkdown template can not run smoothy, I guess that the bcbioRNAseq package have not been updated. For example, the `emapplot(enrich_go, showCategory = 25) ` throw the following error:

> Error in layout_with_kk(structure(list(0, FALSE, numeric(0), numeric(0), : At layout_kk.c:93 : `K' constant must be positive in Kamada-Kawai layout, Invalid value

**Comment by mjsteinbaugh** [comment]
Okay thanks, I'll check this step too.

**Comment by hliu2016** [comment]
@mjsteinbaugh ,
I have inserted this line `gene_list <- sort(gene_list, decreasing = TRUE)` before calling `gseGO `function. However, the resulting gsea_go included no obs. 

I noticed that the `gene_list `actually include all the genes, Maybe the `sig_genes` should be passed to `gseGO `function?

**Comment by mjsteinbaugh** [comment]
Hi @hliu2016 This should be fixed in the newest bcbioRNASeq release (v0.2.4).

**Comment by hliu2016** [comment]
@mjsteinbaugh 
Thanks for update. But I still have a question. The GSEA GO analysis seems to take all genes as input. 

```
gene_list <- 1 - res_df$padj
names(gene_list) <- row.names(res_df)
gene_list <- sort(gene_list, decreasing = TRUE)
glimpse(gene_list)
```

The variable `res_df` is defined as 

```
res <- res[!is.na(res$padj), , drop = FALSE]
res_df <- as.data.frame(res)
```

I speculate that `sig_genes ` should be input to gseGO function, is right?
